#!/bin/bash

# Taken from https://github.com/mathiasbynens/dotfiles/blob/master/.brew
# By way of proxy through https://github.com/jacobian/dotfiles/blob/master/.brew

# Tap some kegs
brew tap homebrew/versions
brew tap homebrew/science
brew tap caskroom/fonts
brew tap d12frosted/emacs-plus
brew tap wagoodman/dive

# Make sure we're up-to-date
brew update

# Now all the awesome stuff. Unfortunately the order here kinda matters
# because of how things build. Ick. So, prereqs:
brew install coreutils
brew install sqlite
brew install readline
brew install caskroom/cask/brew-cask

# Other stuff:
brew install ack
brew install ag
brew install ascii
brew install aspell --with-lang-en
brew install autoconf
brew install automake
brew install bat
brew install cmake
brew install cowsay
brew install direnv
brew install dive
brew install elm
brew install emacs --with-cocoa --with-imagemagick@6 --with-gnutls --with-librsvg --with-mailutils --with-modules --devel
brew install ffmpeg
brew install fish
brew install freetype
brew install gdbm
brew install gettext
brew install gist
brew install git-lfs
brew install gnu-time
brew install gpg
brew install heroku-toolbelt
brew install htop
brew install hub
brew install hugo
brew install jpeg
brew install jq
brew install leiningen
brew install lftp
brew install libevent
brew install libgpg-error
brew install libffi
brew install libksba
brew install libmemcached
brew install libpng
brew install libsvg
brew install libtool
brew install libyaml
brew install markdown
brew install mcrypt
brew install memcached
brew install mercurial
brew install mongodb
brew install moreutils
brew install mtr
brew install mycli
brew install mysql
brew install nmap
brew install node
brew install nvie/tap/git-toolbelt
brew install openssl
brew install ossp-uuid
brew install pandoc
brew install pidof
brew install pipenv
brew install pkg-config
brew install png2ico
brew install pngquant
brew install pv
brew install pwgen
brew install pypy
brew install pyenv
brew install redis
brew install ruby
brew install sbcl
brew install selecta
brew install sloccount
brew install ssh-copy-id
brew install tig
brew install tmux
brew install tree
brew install vim
brew install watch
brew install watchman
brew install wget
brew install wireshark
brew install yarn
brew install youtube-dl
brew install zmq

# Fonts
brew cask install font-inconsolata
brew cask install font-anonymous-pro
brew cask install font-meslo-lg

# Native apps
brew install brew-cask
function installcask() {
    if brew cask info "${@}" | grep "Not installed" > /dev/null; then
        brew cask install "${@}"
    else
        echo "${@} is already installed."
    fi
}

installcask alfred
installcask all2mp3
installcask arq
installcask atext
installcask atom
installcask bartender
installcask charles
installcask coconutbattery
installcask dash
installcask docker
installcask dropbox
installcask firefox
installcask fliqlo
installcask fluid
installcask flux
installcask github
installcask google-drive-file-stream
installcask rowanj-gitx
installcask handbrake
installcask heroku
installcask imageoptim
installcask insomnia
installcask iterm2
installcask java
installcask kaleidoscope
installcask licecap
installcask mailplane
installcask mactex
installcask mou
installcask mysqlworkbench
installcask ngrok
installcask notion
installcask nvalt
installcask peepopen
installcask pgadmin3
installcask postgres
installcask postico
installcask sequel-pro
installcask sketch
installcask slack
installcask slate
installcask sourcetree
installcask spotify
installcask tripmode
installcask versions
installcask viscosity
installcask visual-studio-code
installcask vlc
installcask wireshark
installcask xquartz
installcask zeplin
