#!/bin/bash

# Taken from https://github.com/mathiasbynens/dotfiles/blob/master/.brew
# By way of proxy through https://github.com/jacobian/dotfiles/blob/master/.brew

# Tap some kegs
brew tap homebrew/versions
brew tap homebrew/science
brew tap homebrew/cask-fonts
brew tap daviderestivo/emacs-head
brew tap mongodb/brew

# Make sure we're up-to-date
brew update

# Now all the awesome stuff. Unfortunately the order here kinda matters
# because of how things build. Ick. So, prereqs:
brew install coreutils
brew install sqlite
brew install readline

# Other stuff:
brew install ack
brew install ag
brew install ascii
brew install aspell
brew install autoconf
brew install automake
brew install bat
brew install cask
brew install cmake
brew install cowsay
brew install direnv
brew install emacs-head@28 --with-cocoa --with-imagemagick --with-retro-icon-gnu-head
brew install ffmpeg
brew install fish
brew install freetype
brew install fzf
brew install gdbm
brew install gettext
brew install gist
brew install git-lfs
brew install gnu-time
brew install gnutls
brew install gpg
brew install graphviz
brew install htop
brew install hub
brew install hugo
brew install jpeg
brew install jq
brew install leiningen
brew install lftp
brew install libevent
brew install libgpg-error
brew install libffi
brew install libksba
brew install libmemcached
brew install libpng
brew install libsvg
brew install libtool
brew install libyaml
brew install markdown
brew install mcrypt
brew install memcached
brew install mercurial
brew install mongodb-community@4.2
brew install moreutils
brew install mtr
brew install mycli
brew install mysql
brew install nmap
brew install node
brew install notmuch
brew install nvie/tap/git-toolbelt
brew install openssl
brew install ossp-uuid
brew install pandoc
brew install pidof
# brew install pipenv
brew install pkg-config
brew install png2ico
brew install pngquant
brew install pv
brew install pwgen
brew install pypy
brew install pyenv
brew install redis
brew install ripgrep
brew install ruby
brew install sbcl
brew install selecta
brew install sloccount
brew install ssh-copy-id
brew install tig
brew install tldr
brew install tmux
brew install tree
brew install vim
brew install watch
brew install watchman
brew install wget
brew install yarn
brew install youtube-dl
brew install zmq

# Fonts
brew cask install font-inconsolata
brew cask install font-anonymous-pro
brew cask install font-meslo-lg
brew cask install font-fira-mono
brew cask install font-ia-writer-mono
brew cask install font-ia-writer-duospace

# Native apps
brew install brew-cask
function installcask() {
    if brew cask info "${@}" | grep "Not installed" > /dev/null; then
        brew cask install "${@}"
    else
        echo "${@} is already installed."
    fi
}

installcask alfred
installcask arq
installcask atext
installcask bartender
installcask coconutbattery
installcask dash
installcask docker
installcask fliqlo
installcask fluid
installcask github
installcask rowanj-gitx
installcask handbrake
installcask imageoptim
installcask insomnia
installcask iterm2
installcask java
installcask kaleidoscope
installcask licecap
installcask mactex
installcask ngrok
installcask notion
installcask postgres
installcask sketch
installcask slack
installcask slate
installcask spotify
installcask tableplus
installcask tripmode
installcask versions
installcask viscosity
installcask visual-studio-code
installcask vlc
installcask xquartz
