#!/bin/bash

# Taken from https://github.com/mathiasbynens/dotfiles/blob/master/.brew
# By way of proxy through https://github.com/jacobian/dotfiles/blob/master/.brew

# Tap some kegs
brew tap daviderestivo/emacs-head

# Make sure we're up-to-date
brew update

# Now all the awesome stuff. Unfortunately the order here kinda matters
# because of how things build. Ick. So, prereqs:
brew install coreutils
brew install sqlite
brew install readline

# Other stuff:
brew install ack
brew install ag
brew install ascii
brew install asitop
brew install aspell
brew install autoconf
brew install automake
brew install bat
brew install cask
brew install claude
brew install claude-code
brew install cmake
brew install cowsay
brew install direnv
brew install emacs-head@30 --with-cocoa --with-imagemagick --with-GoldenYak
brew install ffmpeg
brew install fish
brew install freetype
brew install fzf
brew install gdbm
brew install gettext
brew install gist
brew install git-lfs
brew install gnu-time
brew install gnutls
brew install gpg
brew install graphviz
brew install htop
brew install hub
brew install hugo
brew install isync
brew install jpeg
brew install jq
brew install leiningen
brew install lftp
brew install libevent
brew install libgpg-error
brew install libffi
brew install libksba
brew install libmemcached
brew install libpng
brew install libsvg
brew install libtool
brew install libyaml
brew install markdown
brew install memcached
brew install moreutils
brew install msmtp
brew install mtr
brew install mycli
brew install mysql
brew install nmap
brew install node
brew install notmuch
brew install nvie/tap/git-toolbelt
brew install ollama
brew install openssl
brew install ossp-uuid
brew install pandoc
brew install pidof
brew install pkg-config
brew install png2ico
brew install pngquant
brew install pv
brew install pwgen
brew install pypy
brew install redis
brew install ripgrep
brew install ruby
brew install sbcl
brew install selecta
brew install sloccount
brew install ssh-copy-id
brew install svn
brew install tig
brew install tldr
brew install tmux
brew install tree
brew install uv
brew install vim
brew install watch
brew install watchman
brew install wget
brew install yarn
brew install zmq


# Native apps
brew install brew-cask
function installcask() {
    if brew info --cask "${@}" | grep "Not installed" > /dev/null; then
        brew install --cask "${@}"
    else
        echo "${@} is already installed."
    fi
}

installcask rowanj-gitx
installcask handbrake
installcask iterm2
installcask mactex
installcask tableplus
installcask vlc
installcask xquartz
