#!/bin/sh
set -e

pipsi install --python python2 autopep8
pipsi install --python python2 bpython
pipsi install --python python2 cookiecutter
pipsi install --python python2 flake8
pipsi install --python python2 httpie
pipsi install --python python2 ipython
pipsi install --python python2 lice
pipsi install --python python2 pgcli
pipsi install --python python2 pygments
pipsi install --python python2 pylint
pipsi install --python python3 python-fu
pipsi install --python python2 sr
pipsi install --python python2 unp
pipsi install --python python2 watchdog

# Upgrade all pip versions
for pip in ~/.local/venvs/*/bin/pip; do
  eval $pip install --upgrade pip
done
