#!/bin/sh
set -e

pipsi install autopep8
pipsi install bpython
pipsi install cookiecutter
pipsi install flake8
pipsi install httpie
pipsi install ipython
pipsi install lice
pipsi install pgcli
pipsi install pygments
pipsi install pylint
pipsi install python-fu
pipsi install sr
pipsi install unp
pipsi install watchdog

# Upgrade all pip versions
for pip in ~/.local/venvs/*/bin/pip; do
  eval $pip install --upgrade pip
done
