#!/bin/sh
set -e

pipsi install ansible
pipsi install autopep8
pipsi install bpython
pipsi install cookiecutter
pipsi install fabric
pipsi install flake8
pipsi install glances
pipsi install httpie
pipsi install ipython
pipsi install lice
pipsi install pgcli
pipsi install pip-tools
pipsi install pygments
pipsi install pylint
pipsi install python-fu
pipsi install sr
pipsi install tox
pipsi install twine
pipsi install unp
pipsi install watchdog
